version: '3'

services:
  linkee_db:
    container_name: linkee_db
    image: mysql:5
    hostname: "linkeedb"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "linkee_db"
    volumes:
      - ./testdata/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DB_PORT:-3306}:3306

volumes:
  docker-entrypoint-initdb.d:
